name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LUA_VERSION: 5.3.4
      KONG_VERSION: 1.5.0
      LUA_RESTY_OPENIDC_VERSION: 1.7.2
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      # run: sudo apt-get install build-essential libreadline-dev
      run: |
        sudo --no-install-recommends wget gnupg ca-certificates software-properties-common
        wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
        sudo apt-get -y install openresty nginx
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Setup Luarocks and kong
      run: |
        pip install hererocks
        hererocks lua_install -rlatest --lua=${LUA_VERSION}
        export PATH=${PATH}:${PWD}/lua_install/bin

        luarocks install kong ${KONG_VERSION}
        luarocks install lua-resty-openidc ${LUA_RESTY_OPENIDC_VERSION}
        luarocks install lua-cjson
        luarocks install luaunit
        luarocks install luacov
    - name: Run Tests
      run: bash ci/run.sh
