name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LUA_VERSION: 5.3.4
      KONG_VERSION: 1.5.0
      LUA_RESTY_OPENIDC_VERSION: 1.7.2
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install build-essential libreadline-dev
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Setup Luarocks
      run: bash ci/setup.sh
    - name: Run Tests
      run: bash ci/run.sh
